baseURL                = "https://jichang-top.com/"
locale                 = "zh-cn"
title                  = "2026最新稳定高速机场推荐与翻墙梯子测评排行榜 - 机场Top"
defaultContentLanguage = "zh"
hasCJKLanguage         = true
theme                  = "hugo-theme-stack"
enableRobotsTXT        = true

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"


# Sitemap 配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[sitemap.page]
  changefreq = "monthly"
  priority = 0.6

[sitemap.section]
  changefreq = "weekly"
  priority = 0.7

[sitemap.home]
  changefreq = "daily"
  priority = 1.0
